Add implementation for encrypt and decrypt commands.
smallstep/step-kms-plugin pull request #14
Opened 2022-10-19 22:39 UTC by maraino

### Description

This PR adds support for the `encrypt` and `decrypt` commands.

Usage:
```shell
$ step-kms-plugin create --kty RSA --size 2048 --touch-policy always yubikey:slot-id=83
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwBSvezKvl6M0fpeXR4+3
VPjndDSvBAKjPvUCRFy9T3ITSVI6nHbkmTK2sil8GjwolxLKVOcxuTS88CFN8I88
+uRpOTchq+Hqm98sTELavlAsMB2kjqzNfXEP9lc64WwFe5yx5Vwn68IYkDERqt+K
8kX5d0BYHs3fuE32EEMk3NZnEeMKYhEueNVK5LJd+o5nmOheg6aNOXeMOFHpINX0
jjSyk8hUQxljxH6cdvV0ZPFPvCzZzBbXPAApBlWkNcqcYV6PQOkNXJviYnfd4jNb
GmpZ1nTWsb7hu3LuSP/7gCYktFGb0zcScwYmBpSUSdSAk5BN45wejvFYQVCLzonI
FwIDAQAB
-----END PUBLIC KEY-----
$ echo my-super-secret-secret | step-kms-plugin encrypt yubikey:slot-id=83
S0RIjuwh+CQqauxcyOmnBsej645gLwen9D+Iv/29pl6v0pbECg+wKu2upi7MvyXJ2TLzwKsxbGpXST7WHBSMew53op+bZAXxMmYXiuS5Fu+VnDeBBKvjTFVDRro1aOQBE4MpgAT1wdo11mIJrpNfDSYAcFUGCIa+Xhn8y4pxuX1xZFBQHqgs2ZYTyvNllcQUo/Rim3RDtrG6N4WrQK2fccQEMQRBHFTIskRSoJOQ90PrruZmIbzs4NcghThn310WgyW9yVhpKAE6iQk1wrETff9Z2vx8OApU7TK40kGYiV4Tkk/ZeqhDCL/duLNWtA3WuB3p8rcFz4ExgySx2CsBbA==
$ echo S0RI...== | step-kms-plugin decrypt yubikey:slot-id=83
my-super-secret-secret
```

2022-10-24 11:06 UTC, azazeal commented on cmd/decrypt.go
> +		km, err := kms.New(context.Background(), apiv1.Options{
Cobra commands export their own [context](https://pkg.go.dev/github.com/spf13/cobra#Command.Context) and I think we should be using it.

2022-10-24 11:08 UTC, azazeal commented on cmd/encrypt.go
> +		km, err := kms.New(context.Background(), apiv1.Options{
Similar to above, please use the command's [context](https://pkg.go.dev/github.com/spf13/cobra#Command.Context).

2022-10-24 11:09 UTC, azazeal commented on cmd/root.go
> +		fmt.Fprint(os.Stderr, s+": ")
Perhaps check whether the prompt already ends with a `:` before appending your own.

2022-10-24 21:49 UTC, maraino commented on cmd/decrypt.go
> +		km, err := kms.New(context.Background(), apiv1.Options{
Fixed with cb8e1c2

2022-10-24 21:49 UTC, maraino commented on cmd/encrypt.go
> +		km, err := kms.New(context.Background(), apiv1.Options{
Fixed with cb8e1c2

2022-10-24 21:49 UTC, maraino commented on cmd/root.go
> +		fmt.Fprint(os.Stderr, s+": ")
Fixed with 2761710

2022-10-24 23:47 UTC, tashian requested changes

2022-10-24 23:47 UTC, tashian commented on cmd/decrypt.go
> +	Example: `  # Decrypts a input given by stdin using RSA PKCS#1 v1.5:
```suggestion
Not all devices support both schemes. YubiKeys do: they support PKCS #1 v1.5 via the PIV application,
and they support RSA-OAEP via the YubiKey PKCS #11 library, YKCS11.
Other PKCS #11 devices (including YubiHSM2) will generally support both PKCS #1 v.1.5 and RSA-OAEP.`,
	Example: `  # Decrypts a input given by stdin using RSA PKCS#1 v1.5:
```

2022-10-24 23:47 UTC, tashian commented on cmd/encrypt.go
> +	Example: `  # Encrypts a password given by stdin using RSA PKCS#1 v1.5:
```suggestion
All KMSs support encryption, because only the public key is used. Support
for decryption is currently limited to YubiKey and some PKCS #11 KMSs. 
Not all devices support both schemes. YubiKeys do: they support PKCS #1 v1.5 via the PIV application,
and they support RSA-OAEP via the YubiKey PKCS #11 library, YKCS11.
Other PKCS #11 devices (including YubiHSM2) will generally support both PKCS #1 v.1.5 and RSA-OAEP.`,
	Example: `  # Encrypts a password given by stdin using RSA PKCS#1 v1.5:
```

2022-10-24 23:53 UTC, tashian requested changes

2022-10-24 23:53 UTC, tashian commented on cmd/decrypt.go
> +This command supports decrypting a short encrypted message with RSA and the
```suggestion
This command supports decrypting a short encrypted message (eg. a password) with RSA and the
```

2022-10-24 23:53 UTC, tashian commented on cmd/encrypt.go
> +This command supports encrypting a short message with RSA and the padding scheme
```suggestion
This command supports encrypting a short message (eg. a password) with RSA and the padding scheme
```

2022-10-25 00:00 UTC, maraino commented on cmd/decrypt.go
> +	Example: `  # Decrypts a input given by stdin using RSA PKCS#1 v1.5:
Fixed with ccf675d

2022-10-25 19:21 UTC, tashian approved these changes
lgtm

2022-10-25 20:06 UTC, azazeal approved these changes
LGTM; just a minor suggestion.

2022-10-25 20:06 UTC, azazeal commented on cmd/decrypt.go
> +		if l := len(args); l != 1 {
Cobra has an `ExactArgs` [thing](https://github.com/spf13/cobra/blob/10cf7be9972ee5b5994cf760ecba642309ac8685/args.go#L94), maybe use that where you initialize the command, it'll take care of argument count validation for you.

2022-10-25 22:58 UTC, maraino commented on cmd/decrypt.go
> +		if l := len(args); l != 1 {
I'll take that into account for future PRs. I've never used cobra beefore.

2022-10-25 22:59 UTC, merged

2022-10-25 23:07 UTC, maraino commented on cmd/decrypt.go
> +		if l := len(args); l != 1 {
I also show the usage when this happens, which won't happen with `ExactArgs`, but I can create a `PositionalArgs` to behave as I want.

`ExacArgs` shows `Error: accepts 1 arg(s), received 0`