Enable RPM and Deb package uploads to packages.smallstep.com
smallstep/step-kms-plugin pull request #202
Opened 2024-12-11 21:31 UTC by jdoss

This adds support for signing RPM and Deb packages and uploading them to GCP Artifact Registry. It also changes the RPM and Deb file name format to use the ConventionalFileName macro in GoReleaser.

2024-12-17 02:24 UTC, maraino reviewed
It looks good in general, My only concern is that I think this requires goreleaser-pro, and to use goreleaser-cross with goreleaser-pro you need to use a goreleaser-cross-pro image, see https://github.com/goreleaser/goreleaser-cross/pkgs/container/goreleaser-cross-pro

2024-12-17 23:14 UTC, maraino requested changes

2024-12-17 23:14 UTC, maraino commented on scripts/package-repo-import.sh
> +fi
This is perfect, but I don't think github actions sets the environment variable:
```
      - name: Is Pre-release
        id: is_prerelease
        run: |
          set +e
          echo ${{ github.ref }} | grep "\-rc.*"
          OUT=$?
          if [ $OUT -eq 0 ]; then IS_PRERELEASE=true; else IS_PRERELEASE=false; fi
          echo "IS_PRERELEASE=${IS_PRERELEASE}" >> "${GITHUB_OUTPUT}"
```
IS_PRERELASED is not added to ${GITHUB_ENV}

The `make release-dry-run` and `make release-dev` should also set that variables.

2024-12-17 23:14 UTC, maraino commented on Makefile
> +		-e GORELEASER_KEY=${GORELEASER_KEY} \
Add environment variable `IS_PRERELEASE=true`

2024-12-17 23:14 UTC, maraino commented on Makefile
> +		-e GORELEASER_KEY=${GORELEASER_KEY} \
Add environment variable `IS_PRERELEASE=true`

2025-03-18 17:30 UTC, maraino commented on Makefile
>  		--clean --skip=validate --skip=publish
Do we need to add the `--split` flag here? Running `make release-dry-run` should create everything that `make release` create, but it should not upload anything to github, gcp, ...

2025-03-19 00:46 UTC, maraino commented on Makefile
> +		--clean --skip=validate --skip=sign --prepare
Although is the same, for consistency:
```suggestion
		release --clean --skip=validate --skip=sign --prepare
```

2025-03-19 21:09 UTC, dopey commented on .github/workflows/release.yml
> +          IS_PRERELEASE: ${{ needs.create_release.outputs.is_prerelease }}
```suggestion
```

2025-03-19 21:09 UTC, dopey approved these changes

2025-03-19 22:23 UTC, dopey approved these changes

2025-03-24 18:34 UTC, maraino commented on .github/workflows/release.yml
> +          GPG_PRIVATE_KEY_FILE: ${{ env.GPG_PRIVATE_KEY_FILE }}
`make release` is already reading the environment variables from `.release-env`, we should probably use only one way to set this.

2025-03-24 18:34 UTC, maraino commented on Makefile
> +		-e RELEASE_DATE=$(RELEASE_DATE) \
See the previous comment, we can add this to `.release-env`. Or remove it.

2025-03-26 18:32 UTC, maraino approved these changes
lgtm

2025-03-26 18:33 UTC, merged